### ISSUE TITLE
Diffs on long strings fail to show up

### ISSUE THREAD

**Issue by zkat** [tapjs/tapjs#140]
Running a `tap.same` test on two strings that differ only in having `\s` vs `\n`, the diff won't show up if the strings are long enough:

![screen shot 2015-06-04 at 1 39 07 pm](https://cloud.githubusercontent.com/assets/17535/7994299/14b5679e-0ac1-11e5-8e1d-80d6ab6b7b57.png)

With `-bC`:

```
         found:
            - >-
              /Users/zkat/Documents/code/npm/test/tap/outdated/node_modules/async:async@0.2.9:async@0.2.9:async@0.2.10

              /Users/zkat/Documents/code/npm/test/tap/outdated/node_modules/checker:checker@0.5.1:checker@0.5.1:checker@0.5.2

              /Users/zkat/Documents/code/npm/test/tap/outdated/node_modules/underscore:underscore@1.3.1:underscore@1.3.1:underscore@1.5.1
          wanted:
            - '/Users/zkat/Documents/code/npm/test/tap/outdated/node_modules/async:async@0.2.9:async@0.2.9:async@0.2.10 /Users/zkat/Documents/code/npm/test/tap/outdated/node_modules/checker:checker@0.5.1:checker@0.5.1:checker@0.5.2 /Users/zkat/Documents/code/npm/test/tap/outdated/node_modules/underscore:underscore@1.3.1:underscore@1.3.1:underscore@1.5.1'
          at:
            file: test/tap/outdated.js
            line: 107
            column: 15
```

They _do_ show up with shorter strings, though:

```
not ok should be equivalent
    +++ found
    --- wanted
     [
    -  "x
    -y"
    +  "x y"
     ]
```
