### ISSUE TITLE
v4 failing tests on windows

### ISSUE THREAD

**Issue by isaacs** [tapjs/tapjs#202]
Haven't dug into this, leaving here so I don't forget.  Running tests with coverage fails in a weird way on node v4.  Looks like a spawn-wrap bug maybe?

```
not ok 8 - Error: spawn UNKNOWN
  ---
  at:
    file: util.js
    line: 870
    column: 11
    function: exports._errnoException
  code: UNKNOWN
  errno: UNKNOWN
  syscall: spawn
  test: TAP
  message: 'Error: spawn UNKNOWN'
  stack: "exports._errnoException (util.js:870:11)\nChildProcess.spawn (internal/child_process.js:298:11)\nChildProcess.spawn (node_modules\\nyc\\node_modules\\spawn-wrap\\index.js:138:18)\nexports.spawn (child_process.js:362:9)\nTest.spawnTest [as spawn] (lib\\test.js:9:38042)\nTest._processQueue (lib\\test.js:9:50895)\nChildProcess.onclose (lib\\test.js:9:43112)\nmaybeClose (internal/child_process.js:818:16)\n"
  ...
```

Stack:

```
exports._errnoException (util.js:870:11)
ChildProcess.spawn (internal/child_process.js:298:11)
ChildProcess.spawn (node_modules\nyc\node_modules\spawn-wrap\index.js:138:18)
exports.spawn (child_process.js:362:9)
Test.spawnTest [as spawn] (lib\test.js:9:38042)
Test._processQueue (lib\test.js:9:50895)
ChildProcess.onclose (lib\test.js:9:43112)
maybeClose (internal/child_process.js:818:16)
```
