### ISSUE TITLE
tap-parser@1.3.x introduced regression

### ISSUE THREAD

**Issue by rmg** [tapjs/tapjs#281]
When tap-parser@1.3.0/1.3.1 was published it caused `tap` to start failing tests that were previously passing. The failures have no indication of why they are failing.

Example of the less than helpful output:

```
test/test-runner.js ................................. 11/12
  not ok test/test-runner.js
    timeout: 30000
    arguments:
      - test/test-runner.js
    command: /Users/ryan/.nvm/versions/node/v4.4.7/bin/node
    file: test/test-runner.js
    results:
      pass: 1
      plan:
        start: 1
        end: 1
      ok: false
      count: 1

total ............................................... 11/12


  11 passing (1s)
  1 failing
```

Installing tap-parser@1.2.x and then re-running the test results in the expected behaviour:

```
test/test-runner.js ................................. 11/11
total ............................................... 11/11

  11 passing (1s)

  ok
```

Ref: https://github.com/tapjs/tap-parser/issues/36#issuecomment-239056359
