### ISSUE TITLE
files not loaded from .taprc

### ISSUE THREAD

**Issue by jhessin** [tapjs/tapjs#438]
My package.json test script runs `TAP_RCFILE=./.taprc tap` and my `.taprc` file looks like this:

```yaml
color: true
reporter: tap
files: [ ./test.js ]
```

Expected result: running `yarn test` will run the tests in test.js.

Actual result: I get a usage blob from running `yarn test`

Workaround: I can get the expected result if I append a `--` to the end of the script. Why is this?
