### ISSUE TITLE
before and after scripts do not run under esm

### ISSUE THREAD

**Issue by coreyfarrell** [tapjs/tapjs#617]
Take the following configuration:
```yaml
esm: true
before: scripts/before.js
after: scripts/after.js
```

I know you expressed an interest in disabling `esm` by default but I think the expectation is that these scripts should be executed with `node -r esm` if esm is enabled (especially if it's explicit as may be the case in tap 15).
