### ISSUE TITLE
Test suite randomly fails with "No Tests Found" for all test files

### ISSUE THREAD

**Issue by nhtruong** [tapjs/tapjs#840]
Hello!
One of our Github workflows runs a matrix of 24 jobs with different configurations. Each job runs the same 4 test files. However, occasionally, one or two of these jobs will randomly fail with the exact same `no tests found` error for all 4 files:

```
# Subtest: test/integration/helpers/bulk.test.js
    1..0 # no tests found
not ok 1 - test/integration/helpers/bulk.test.js # time=30018.69ms
  ---
  env: {}
  file: test/integration/helpers/bulk.test.js
  timeout: 30000
  command: /opt/hostedtoolcache/node/16.17.0/x64/bin/node
  args:
    - test/integration/helpers/bulk.test.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: /home/runner/work/opensearch-js/opensearch-js
  exitCode: null
  signal: SIGTERM
```
Here's the log of the Gihub action: https://github.com/opensearch-project/opensearch-js/actions/runs/3153469277/jobs/5129983094#step:7:89

Is this a race condition on our end or is it a node-tap bug?

Thank you.
