### ISSUE TITLE
[BUG] Cannot use import syntax in tests

### ISSUE THREAD

**Issue by paambaati** [tapjs/tapjs#968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

This is very similar to https://github.com/tapjs/tapjs/issues/946 – I'm migrating a TS project from `tape` to the latest version of `tap`, and I run into this error –

```
SyntaxError: Cannot use import statement outside a module
```

**Full output**
```
$ npx tap run test/main.test.ts

/my-project/test/main.test.ts:1
import t from 'tap';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._compile (/my-project/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .ts] (/my-project/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)

Node.js v21.1.0


  🌈 TEST COMPLETE 🌈


 FAIL  test/main.test.ts 0 289ms

Asserts:  0 pass  1 fail  1 of 1 complete
Suites:   0 pass  1 fail  1 of 1 complete

# No coverage generated
# { total: 1, pass: 0, fail: 1 }
# time=363.258ms
```

### Reproduction

1. Clone the repo + branch at https://github.com/paambaati/codeclimate-action/tree/test/use-tap
2. Install all dependencies with `npm install`
3. Run the main test file with `npx tap run test/main.test.ts`
4. See the error occuring.

### Environment

```
$ which tap
tap not found

$ npm ls tap
my-project@5.0.0 /my-project
└── tap@18.5.4

$ npx tap versions
tap: 18.5.4
"@tapjs/config": 2.4.10
"@tapjs/core": 1.4.3
"@tapjs/run": 1.4.11
"@tapjs/stack": 1.2.7
"@tapjs/test": 1.3.14
tap-parser: 15.3.1
tap-yaml: 2.2.1
tcompare: 6.4.4
plugins:
  "@tapjs/after": 1.1.14
  "@tapjs/after-each": 1.1.14
  "@tapjs/asserts": 1.1.14
  "@tapjs/before": 1.1.14
  "@tapjs/before-each": 1.1.14
  "@tapjs/filter": 1.2.14
  "@tapjs/fixture": 1.2.14
  "@tapjs/intercept": 1.2.14
  "@tapjs/mock": 1.2.12
  "@tapjs/node-serialize": 1.2.3
  "@tapjs/snapshot": 1.2.14
  "@tapjs/spawn": 1.1.14
  "@tapjs/stdin": 1.1.14
  "@tapjs/typescript": 1.3.3
  "@tapjs/worker": 1.1.14

$ npx tap config list
# vim: set filetype=yaml :
color: true
coverage-report:
  - text
exclude:
  - "**/@(fixture*(s)|dist)/**"
include:
  - "**/@(test?(s)|__test?(s)__)/**/*.@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/*.@(test?(s)|spec).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/test?(s).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
jobs: 6
reporter: base
snapshot-clean-cwd: true
timeout: 30

$ tap plugin list
@tapjs/after
@tapjs/after-each
@tapjs/asserts
@tapjs/before
@tapjs/before-each
@tapjs/filter
@tapjs/fixture
@tapjs/intercept
@tapjs/mock
@tapjs/node-serialize
@tapjs/snapshot
@tapjs/spawn
@tapjs/stdin
@tapjs/typescript
@tapjs/worker

# if using typescript:
$ npm ls ts-node
my-project@5.0.0 /my-project
└── ts-node@10.9.1

$ npm ls typescript
my-project@5.0.0 /my-project
├─┬ @openpgp/web-stream-tools@0.0.14
│ └── typescript@5.2.2 deduped
├─┬ tap@18.5.4
│ └─┬ @tapjs/test@1.3.14
│   ├─┬ @isaacs/ts-node-temp-fork-for-pr-2009@10.9.1
│   │ └── typescript@5.2.2 deduped
│   ├─┬ tshy@1.7.0
│   │ └── typescript@5.2.2 deduped
│   └── typescript@5.2.2 deduped
├─┬ ts-node@10.9.1
│ └── typescript@5.2.2 deduped
└── typescript@5.2.2

# posix:
uname -a
Darwin Wintermute 22.6.0 Darwin Kernel Version 22.6.0: Wed Oct  4 21:26:43 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_ARM64_T8112 arm64
```

**Comment by paambaati** [comment]
**Output from `-Rtap`**

```
Node.js v21.1.0
# Subtest: test/main.test.ts
    1..0 # no tests found
not ok 1 - test/main.test.ts # time=278.198ms
  ---
  stdio: inherit
  cwd: /my-project
  externalID: test/main.test.ts
  command: /Users/me/Library/Application
    Support/fnm/node-versions/v21.1.0/installation/bin/node
  args:
    - --import=file:///my-project/node_modules/@tapjs/mock/dist/esm/import.mjs
    - --loader=file:///my-project/node_modules/@isaacs/ts-node-temp-fork-for-pr-2009/esm.mjs
    - --no-warnings
    - --enable-source-maps
    - --import=file:///my-project/node_modules/@tapjs/processinfo/dist/esm/import.mjs
    - /my-project/test/main.test.ts
  context: !symbol/shared tap.isRunner
  exitCode: 1
  signal: null
  ...

# No coverage generated
# { total: 1, pass: 0, fail: 1 }
# time=322.759ms
```
